### PR TITLE
Added Profile Screen

### LINKED ISSUE #2: Complete Profile Page
Add user profile photo. Add text fields for name and country.

### PR DESCRIPTION
**Pull request by Perumallpardhiv**
Fixes : #2 

Added Profile Page

https://user-images.githubusercontent.com/96647299/197256734-9be654f7-9264-48f3-ac8a-eaea1f85fbd5.mp4

### CODE REVIEW

**Comment by Perumallpardhiv** [comment]
@chinmayilondhe 

Is there any problem if I am getting like this ?

image

**Comment by chinmayilondhe** [comment]
No, @Perumallpardhiv It's related to github actions I'll fix that.

**Comment by Perumallpardhiv** [comment]
> No, @Perumallpardhiv It's related to github actions I'll fix that.

Thank you
Pls review this pr

**Comment by chinmayilondhe** [comment]
Hi @Perumallpardhiv 

image
Could you please remove this tabBar in profile screen page?

**Comment by Perumallpardhiv** [comment]
Ok I will try

**Comment by Perumallpardhiv** [comment]
Can I pr updated one in this same branch or any need to create new branch ?

**Comment by Perumallpardhiv** [comment]
@chinmayilondhe 

Removed TabBar

Continue of #7  which fixes: #2 

https://user-images.githubusercontent.com/96647299/197327478-20a23809-44eb-41fb-a02f-2c53d94a5d59.mp4

**Comment by chinmayilondhe** [comment]
Good @Perumallpardhiv

**Pull request merged**
